language: generic

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang
      env: CC='/usr/bin/clang' EXTRA='--disable-fortran2003 --disable-openmp' XRL_PYTHON2='/usr/bin/python' XRL_PYTHON3='/usr/bin/python3'
    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - gfortran-7
      env: CC='gcc-7' FC='gfortran-7' XRL_PYTHON2='/usr/bin/python' XRL_PYTHON3='/usr/bin/python3'
    - os: osx
      osx_image: xcode7.3
      env: CC='clang' EXTRA='--disable-fortran2003 --disable-openmp' XRL_PYTHON2='/usr/local/opt/python@2/bin/python2' XRL_PYTHON3='/usr/local/bin/python3' CFLAGS='-O0' PHP='/usr/local/opt/php@5.6/bin/php' PHP_CONFIG='/usr/local/opt/php@5.6/bin/php-config' PHP_BREW='php@5.6'
    - os: osx
      osx_image: xcode7.3
      env: CC='clang' EXTRA='--disable-fortran2003 --disable-openmp' XRL_PYTHON2='/usr/local/opt/python@2/bin/python2' XRL_PYTHON3='/usr/local/bin/python3' CFLAGS='-O0' PHP='/usr/local/bin/php' PHP_CONFIG='/usr/local/bin/php-config' PHP_BREW='php'
    - os: osx
      osx_image: xcode7.3
      env: CC='gcc-7' FC='gfortran-7' XRL_PYTHON2='/usr/local/opt/python@2/bin/python2' XRL_PYTHON3='/usr/local/bin/python3'

before_install:
  - |
    if [ $TRAVIS_OS_NAME == linux ] ; then
      sudo apt-get --yes --force-yes update
      sudo apt-get --yes --force-yes install python-all-dev python-numpy cython python3-all-dev python3-numpy fpc gfortran php5-dev lua5.2 liblua5.2-dev
    fi
  - |
    if [ $TRAVIS_OS_NAME == osx ] ; then
      brew cask uninstall --force oclint
      brew uninstall --force --ignore-dependencies $(brew list) || exit 1
      brew update || exit 1
      brew cleanup -s || exit 1
      rm -rf $(brew --cache) || exit 1
      brew install autoconf automake libtool gcc@7 swig ruby python@2 python fpc lua perl ${PHP_BREW}
      /usr/local/opt/python@2/bin/pip2.7 install Cython numpy
      /usr/local/bin/pip3 install numpy
    fi
  - rm -rf $HOME/.phpenv

install:
  - |
    if [ $TRAVIS_OS_NAME == linux ]; then
      wget http://prdownloads.sourceforge.net/swig/swig-3.0.12.tar.gz || exit 1
      tar xfz swig-3.0.12.tar.gz || exit 1
      cd swig-3.0.12 || exit 1
      ./configure || exit 1
      make || exit 1
      sudo make install || exit 1
      cd ..
    fi

script:
  - autoreconf -fi || exit 1
  - ./configure --enable-php --enable-pascal --enable-java --disable-python --disable-python-numpy || exit 1
  - make || exit 1
  - make check || exit 1
  - make distclean || exit 1
  - ./configure --disable-all-bindings CFLAGS="-std=c89 -pedantic" || exit 1
  - make || exit 1
  - make check || exit 1
  - make distclean || exit 1
  - ./configure --enable-python-numpy --enable-python PYTHON=${XRL_PYTHON2} ${EXTRA} || exit 1
  - make || exit 1
  - make check || exit 1
  - make distclean || exit 1
  - ./configure --enable-python-numpy --enable-python PYTHON=${XRL_PYTHON3} ${EXTRA} || exit 1
  - make || exit 1
  - make check || exit 1
  - if [ "$TRAVIS_OS_NAME" == "linux" ] ; then PYTHON=${XRL_PYTHON2} make distcheck || exit 1 ; fi

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - Tom.Schoonjans@me.com
    on_success: never
    on_failure: always

