language: generic

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang
      env: CC='clang' EXTRA='--disable-fortran2003 --disable-openmp' XRL_PYTHON='/usr/bin/python' XRL_PYTHON3='/usr/bin/python3'
    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - gfortran-5
      env: CC='gcc-5' FC='gfortran-5' XRL_PYTHON='/usr/bin/python' XRL_PYTHON3='/usr/bin/python3'
    - os: osx
      env: CC='clang' EXTRA='--disable-fortran2003 --disable-openmp' XRL_PYTHON='/usr/local/bin/python' XRL_PYTHON3='/usr/local/bin/python3'
    - os: osx
      env: CC='gcc-5' FC='gfortran-5' XRL_PYTHON='/usr/local/bin/python' XRL_PYTHON3='/usr/local/bin/python3'

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get --yes --force-yes update && sudo apt-get --yes --force-yes install python-all-dev python-numpy cython python3-all-dev python3-numpy fpc gfortran php5-dev lua5.2 liblua5.2-dev ; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install homebrew/versions/gcc5 swig ruby python python3 fpc lua perl && pip install Cython numpy && pip3 install numpy ; fi

install:
  - |
    if [ $TRAVIS_OS_NAME == linux ]; then
      wget http://prdownloads.sourceforge.net/swig/swig-3.0.10.tar.gz || exit 1
      tar xfz swig-3.0.10.tar.gz || exit 1
      cd swig-3.0.10 || exit 1
      ./configure || exit 1
      make || exit 1
      sudo make install || exit 1
      cd ..
    fi

script:
  - autoreconf -fi
  - ./configure --enable-php --enable-pascal --disable-python --disable-python-numpy && make && make check && make distclean
  - ./configure --disable-all-bindings CFLAGS="-std=c89 -pedantic" && make && make check && make distclean
  - ./configure --enable-python-numpy --enable-python PYTHON=${XRL_PYTHON} ${EXTRA} && make && make check && make distclean
  # there appears to be a problem on OSX with python 3.5.2, Cython and clang... disable for now...
  - if [ $TRAVIS_OS_NAME == linux ]; then ./configure --enable-python-numpy --enable-python PYTHON=${XRL_PYTHON3} ${EXTRA} && make && make check && make distclean ; fi

branches:
  only:
    - master
    - molecular-weight

notifications:
  email:
    recipients:
      - Tom.Schoonjans@me.com
    on_success: never
    on_failure: always

